name: Introduction SvelteKit Examples Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1

      - name: Yarn Install
        working-directory: ./examples/sveltekit-adapter-aws
        run: yarn

      - name: Build and Deploy
        working-directory: ./examples/sveltekit-adapter-aws
        run: yarn build
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_AWS_REGION: us-east-1
